# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
mainConfiguration: https://github.com/WebstoneHQ/courses

tasks:
  - before: npm i -g pnpm
    init: pnpm install
    command: |
      gp sync-done pnpm-install
      pnpm start
  - command: |
      gp sync-await pnpm-install
      pnpm dev

ports:
  - port: 8080
    description: Lessons
    onOpen: open-browser
