on:
  repository_dispatch:
    types: [on_new_content_available]

jobs:
  open-pr-in-student-repo:
    if: github.repository_owner == 'WebstoneHQ'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      COURSE_PATH: ${{ format('courses/{0}/{1}/{2}', github.event.client_payload.course.id, github.event.client_payload.course.stackgroup, github.event.client_payload.course.stack) }}
    steps:
      - name: Clone the `WebstoneHQ/courses` repo
        uses: actions/checkout@v3
        with:
          path: courses
          persist-credentials: false
          ref: main
          repository: WebstoneHQ/courses
          ssh-key: ${{ secrets.COURSES_REPO_PRIVATE_DEPLOY_KEY }}
      - name: Clone the student repo fork
        uses: actions/checkout@v3
        with:
          path: student-repo-fork
      - name: Verify the student's fork contains the course
        if: hashFiles(format('student-repo-fork/{0}/package.json', env.COURSE_PATH)) == ''
        uses: actions/github-script@v6
        with:
          script: core.setFailed(`Course ${process.env.COURSE_PATH} does not exist.`)
      - name: Copy course content
        working-directory: student-repo-fork
        run: |
          git switch -c ${{ github.event.client_payload.git.branch }}
          mkdir -p ./${{ env.COURSE_PATH }}
          cp -r ../courses/${{ env.COURSE_PATH }} ./${{ env.COURSE_PATH }}
          git config user.name "Webstone Education Bot"
          git config user.email github-bot@webstonehq.com
          git add ./${{ env.COURSE_PATH }}
          git commit -m "${{ github.event.client_payload.git.commitmessage }}"
          git push --set-upstream origin ${{ github.event.client_payload.git.branch }}
      - name: Open a PR in the student repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WEBSTONE_BOT_PAT }}
          script: |
            const { studentrepo, pr } = context.payload.client_payload;
            const result = await github.rest.pulls.create({
              title: pr.title,
              owner: studentrepo.split("/")[0],
              repo: studentrepo.split("/")[1],
              head: 'WebstoneHQ:${{ github.event.client_payload.git.branch }}',
              base: 'main',
              body: pr.description
            });
