on:
  repository_dispatch:
    types: [on_signup]

jobs:
  open-pr-in-student-repo-with-first-course:
    uses: ./.github/workflows/open-pr-in-student-repo.yml
    with:
      coursepath: ${{ format('courses/{0}/{1}/{2}', github.event.client_payload.course.id, github.event.client_payload.course.stackgroup, github.event.client_payload.course.stack) }}
      gitBranch: ${{ github.event.client_payload.git.branch }}
      gitCommitMessage: ${{ github.event.client_payload.git.commitmessage }}
      mustHaveCourse: false
      prDescription: ${{ github.event.client_payload.pr.description }}
      prTitle: ${{ github.event.client_payload.pr.title }}
      studentRepoName: ${{ github.event.client_payload.studentrepo.name }}
      studentRepoOwner: ${{ github.event.client_payload.studentrepo.owner }}
    secrets: inherit
